target-version = "py310"
line-length = 100

[lint]
ignore = [
  "D203", # 1 blank line required before class docstring
  "D213", # Multi-line docstring summary should start at the second line
]
select = [
  "A", # flake8-builtins
  "ARG", # flake8-unused-arguments
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "D", # pydocstyle
  "E", # pycodestyle errors
  "EM", # flake8-errmsg
  "EXE", # flake8-executable
  "F", # pyflakes
  "FA", # flake8-future-annotations
  "FLY", # flynt
  "G", # flake8-logging-format
  "I", # isort
  "ISC", # flake8-implicit-str-concat
  "N", # pep8-naming
  "PGH", # pygrep-hooks
  "PIE", # flake8-pie
  "PTH", # flake8-use-pathlib
  "Q", # flake8-quotes
  "RET", # flake8-return
  "RSE", # flake8-raise
  "RUF", # ruff-specific rules
  "SIM", # flake8-simplify
  "UP", # pyupgrade
  "W", # pycodestyle warnings
]
