name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: bboe/.github/.github/workflows/pypi-publish.yml@main
    with:
      url: https://pypi.org/project/ext_http_server/